language: python
python:
  - "3.4"
  - "3.5"
# command to run tests
install:
  - pip install pandas

script:
  - python TestAdddoc.py
  - python TestDoctordb.py
  - python testinsdose_mod.py
  - python testmedmgr_mod.py
